default_language_version:
  python: python3.10
  node: "14.13.0"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-ast
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: end-of-file-fixer
      - id: mixed-line-ending
      # - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: no-commit-to-branch
        args:
          [
            "--branch",
            "main",
            "--branch",
            "production",
            "--pattern",
            "Release.*",
          ]
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.12.0
  #   hooks:
  #     - id: isort
  #       args: ["--profile", "black"]
  # - repo: https://github.com/ambv/black
  #   rev: 23.1.0
  #   hooks:
  #     - id: black
  #       # entry: bash -c 'black "$@"; git add -u' --
  #       language_version: python3.10
  #       # args: [--line-length=150]
  #       additional_dependencies: ["click==8.0.4"]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        types: [python]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.2.1"
    hooks:
      - id: prettier
        files: '\.(css|less|scss|ts|tsx|graphql|gql|json|js|jsx|md|yaml|yml|html)$'
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.35.0
    hooks:
      - id: eslint
        files: '\.(css|less|scss|ts|tsx|graphql|gql|json|js|jsx|md|yaml|yml|html|vue)$'
        # additional_dependencies:
        #   - typescript@4.3.5
        #   - "@typescript-eslint/eslint-plugin@4.28.5"
        #   - "@typescript-eslint/parser@4.28.5"
        #   - eslint-plugin-vue@7.14.0
        #   - vue-eslint-parser@7.9.0
        #   - eslint-config-prettier@8.3.0
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
        args: ["--skip", "B608"]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.2
    hooks:
      - id: autopep8
  # - repo: https://github.com/returntocorp/semgrep
  #   rev: "v1.14.0"
  #   hooks:
  #     - id: semgrep
  #       args:
  #         [
  #           "--exclude",
  #           "*.ipynb",
  #           "--exclude",
  #           "*.yml",
  #           "--exclude",
  #           "*.yaml",
  #           "--exclude",
  #           "*.sh",
  #           "--exclude",
  #           "*.tpl",
  #           "--exclude",
  #           "*.json",
  #           "--config",
  #           "p/python",
  #           --config,
  #           "p/flask",
  #           "--config",
  #           "p/r2c-ci",
  #           "--config",
  #           "p/xss",
  #           "--config",
  #           "p/javascript",
  #           "--config",
  #           "p/nginx",
  #           "--config",
  #           "p/docker",
  #           "--config",
  #           "p/docker",
  #           "--config",
  #           "p/ascof22.all_python_rules",
  #           "--error",
  #           "--disable-version-check",
  #           "--timeout",
  #           "300",
  #         ]
